import React, { useState } from 'react';
import { X, Copy, Download, FileCode, Check, Terminal, FileText } from 'lucide-react';
import { loadTokens } from './TokenSettingsModal';
import { normalizeModelFolder } from '../data/comfyuiFolders';

export function ScriptExporter({ isOpen, onClose, modelsList, selectedWorkflows }) {
  const [exportType, setExportType] = useState('download_txt'); // 'download_txt' | 'download_py' | 'json'
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const { hfToken, civitaiToken } = loadTokens();

  // Helper: apply civitai token to URL
  const applyCivitai = (url) => {
    if (!civitaiToken || !url.includes('civitai.com') || url.includes('token=')) return url;
    const sep = url.includes('?') ? '&' : '?';
    return `${url}${sep}token=${civitaiToken}`;
  };

  // Generate output content based on exportType
  let outputContent = '';

  if (exportType === 'download_txt') {
    outputContent = `# --------------------------------------------------------\n`;
    outputContent += `# SimplePod ComfyUI Model Download List\n`;
    outputContent += `# Generated for ${selectedWorkflows.length} selected workflow(s)\n`;
    if (hfToken) outputContent += `# HuggingFace token configured (set in API Tokens settings)\n`;
    if (civitaiToken) outputContent += `# CivitAI token configured — applied to civitai.com URLs\n`;
    outputContent += `# --------------------------------------------------------\n\n`;

    modelsList.forEach(m => {
      if (!m.url) return;
      const folder = normalizeModelFolder(m.folder);
      const resolvedUrl = applyCivitai(m.url);
      if (m.name && m.name !== m.url.split('/').pop()) {
        outputContent += `${resolvedUrl} ${folder} ${m.name}\n`;
      } else {
        outputContent += `${resolvedUrl} ${folder}\n`;
      }
    });
  } else if (exportType === 'download_py') {
    outputContent = `import os
import shutil
import sys
import subprocess
import time
import requests

# Ensure huggingface_hub is installed
try:
    from huggingface_hub import hf_hub_download
except ImportError:
    print("huggingface_hub not found. Installing...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-U", "huggingface_hub"])
    from huggingface_hub import hf_hub_download

# ─── API TOKENS ────────────────────────────────────────────────────────────────
HF_TOKEN = "${hfToken || 'YOUR_HF_TOKEN_HERE'}"
CIVITAI_TOKEN = "${civitaiToken || 'YOUR_CIVITAI_TOKEN_HERE'}"
# ───────────────────────────────────────────────────────────────────────────────

# Configure HuggingFace authentication
if HF_TOKEN and HF_TOKEN != "YOUR_HF_TOKEN_HERE":
    import huggingface_hub
    huggingface_hub.login(token=HF_TOKEN, add_to_git_credential=False)

MODELS_BASE = "/workspace/ComfyUI/models"
MAX_RETRIES = 3

# Model Downloads Array generated by SimplePod Model Calculator
DOWNLOAD_ITEMS = [\n`;

    modelsList.forEach(m => {
      if (m.url) {
        outputContent += `    {"url": "${m.url}", "folder": "${normalizeModelFolder(m.folder)}", "name": "${m.name || ''}"},\n`;
      }
    });

    outputContent += `]

print(f"Starting download of {len(DOWNLOAD_ITEMS)} models...")

for item in DOWNLOAD_ITEMS:
    hf_url = item["url"]
    target_folder = item["folder"].strip("/ ")
    new_filename = item["name"] if item.get("name") else None
    dest_folder = os.path.join(MODELS_BASE, target_folder)
    os.makedirs(dest_folder, exist_ok=True)

    if "huggingface.co" in hf_url and "resolve" in hf_url:
        url_parts = hf_url.split("/")
        idx = url_parts.index("resolve")
        repo_id = "/".join(url_parts[3:idx])
        revision = url_parts[idx + 1]
        filename_in_repo = "/".join(url_parts[idx + 2:])
        original_name = os.path.basename(filename_in_repo)

        final_name = new_filename if new_filename else original_name
        dest_path = os.path.join(dest_folder, final_name)

        print(f"Downloading (HF): {final_name} -> {dest_folder}")
        for attempt in range(MAX_RETRIES):
            try:
                cached_file = hf_hub_download(repo_id=repo_id, filename=filename_in_repo, revision=revision)
                shutil.copy2(cached_file, dest_path)
                print(f"✔ Completed: {dest_path}")
                break
            except Exception as e:
                print(f"  Attempt {attempt+1}/{MAX_RETRIES} failed: {e}")
                if attempt == MAX_RETRIES - 1:
                    print(f"❌ Failed after {MAX_RETRIES} attempts: {hf_url}")
                time.sleep(2)
    else:
        # BUG-9 fix: handle non-HuggingFace URLs (CivitAI, direct CDN, etc.)
        original_name = new_filename if new_filename else hf_url.split("?")[0].split("/")[-1] or "model.safetensors"
        dest_path = os.path.join(dest_folder, original_name)

        print(f"Downloading (direct): {original_name} -> {dest_folder}")
        for attempt in range(MAX_RETRIES):
            try:
                r = requests.get(hf_url, stream=True, timeout=60)
                r.raise_for_status()
                with open(dest_path, "wb") as f:
                    for chunk in r.iter_content(chunk_size=8192):
                        f.write(chunk)
                print(f"✔ Completed: {dest_path}")
                break
            except Exception as e:
                print(f"  Attempt {attempt+1}/{MAX_RETRIES} failed: {e}")
                if attempt == MAX_RETRIES - 1:
                    print(f"❌ Failed after {MAX_RETRIES} attempts: {hf_url}")
                time.sleep(2)
`;

  } else if (exportType === 'json') {
    outputContent = JSON.stringify(modelsList, null, 2);
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(outputContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFile = () => {
    const filename = exportType === 'download_txt' ? 'download.txt' : exportType === 'download_py' ? 'download.py' : 'models.json';
    const blob = new Blob([outputContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-md">
      <div className="w-full max-w-3xl glass-panel rounded-2xl p-6 border border-white/10 shadow-2xl relative animate-in fade-in zoom-in duration-200">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-white/10 mb-4">
          <h3 className="text-lg font-bold text-white flex items-center gap-2">
            <Terminal className="w-5 h-5 text-cyan-400" />
            Export Model Download Scripts
          </h3>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Format Selector Pills */}
        <div className="flex bg-slate-900/80 p-1 rounded-xl border border-white/10 mb-4 text-xs font-semibold">
          <button
            onClick={() => setExportType('download_txt')}
            className={`flex-1 py-2 rounded-lg flex items-center justify-center gap-2 transition-all ${
              exportType === 'download_txt' ? 'bg-violet-600 text-white shadow-md' : 'text-slate-400 hover:text-white'
            }`}
          >
            <FileText className="w-4 h-4" />
            <span>download.txt</span>
          </button>

          <button
            onClick={() => setExportType('download_py')}
            className={`flex-1 py-2 rounded-lg flex items-center justify-center gap-2 transition-all ${
              exportType === 'download_py' ? 'bg-violet-600 text-white shadow-md' : 'text-slate-400 hover:text-white'
            }`}
          >
            <FileCode className="w-4 h-4" />
            <span>download.py (Python Script)</span>
          </button>

          <button
            onClick={() => setExportType('json')}
            className={`flex-1 py-2 rounded-lg flex items-center justify-center gap-2 transition-all ${
              exportType === 'json' ? 'bg-violet-600 text-white shadow-md' : 'text-slate-400 hover:text-white'
            }`}
          >
            <span>JSON Report</span>
          </button>
        </div>

        {/* Code Preview Box */}
        <div className="relative mb-5">
          <pre className="w-full h-80 p-4 rounded-xl bg-slate-950/90 border border-white/10 text-xs font-mono text-cyan-300 overflow-auto scrollbar-thin">
            {outputContent}
          </pre>
          
          <button
            onClick={handleCopy}
            className="absolute top-3 right-3 px-3 py-1.5 rounded-lg bg-slate-800/80 hover:bg-slate-700 text-xs font-semibold text-white border border-white/10 flex items-center gap-1.5 transition-all shadow-md"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-emerald-400">Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Code</span>
              </>
            )}
          </button>
        </div>

        {/* Action Controls */}
        <div className="flex items-center justify-between border-t border-white/10 pt-4">
          <div className="text-xs text-slate-400">
            Contains <strong className="text-white font-mono">{modelsList.filter(m => m.url).length}</strong> downloadable links
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-medium"
            >
              Close
            </button>
            <button
              onClick={handleDownloadFile}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white text-xs font-semibold shadow-lg shadow-violet-600/30 transition-all"
            >
              <Download className="w-4 h-4" />
              <span>Download File</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
